// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface DeezerSearchResp {
    data:  DeezerSearchSearchRespItem[];
    total: number;
    next:  string;
}

export interface DeezerSearchSearchRespItem {
    id:                      number;
    readable:                boolean;
    title:                   string;
    title_short:             string;
    title_version?:          TitleVersion;
    link:                    string;
    duration:                number;
    rank:                    number;
    explicit_lyrics:         boolean;
    explicit_content_lyrics: number;
    explicit_content_cover:  number;
    preview:                 string;
    md5_image:               string;
    artist:                  Artist;
    album:                   Album;
    type:                    DatumType;
}

interface Album {
    id:           number;
    title:        string;
    cover:        string;
    cover_small:  string;
    cover_medium: string;
    cover_big:    string;
    cover_xl:     string;
    md5_image:    string;
    tracklist:    string;
    type:         AlbumType;
}

enum AlbumType {
    Album = "album",
}

interface Artist {
    id:             number;
    name:           string;
    link:           string;
    picture:        string;
    picture_small:  string;
    picture_medium: string;
    picture_big:    string;
    picture_xl:     string;
    tracklist:      string;
    type:           ArtistType;
}

enum ArtistType {
    Artist = "artist",
}

enum TitleVersion {
    Empty = "",
    RemasteredVersion = "(Remastered Version)",
}

enum DatumType {
    Track = "track",
}
